version: "3.7"
services:
  db:
    image: postgres:15-alpine
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: yoco
      POSTGRES_DB: ory_kratos
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: redis-server --save 5 1 --loglevel warning

volumes:
  db-data: null
  redis-data: null
